name: Pull Request
description: Template for creating a new pull request
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check if your PR fulfills the following requirements
      options:
        - label: Unit tests have been added, if needed
        - label: Documentation has been updated, if needed
        - label: Build was run locally and any changes were pushed
        - label: Lint has passed locally without error
        - label: CHANGELOG.md have been updated

  - type: checkboxes
    id: pr-type
    attributes:
      label: PR Type
      description: What type of change does this PR introduce?
      options:
        - label: Bugfix
        - label: Feature
        - label: Code style update (formatting, renaming)
        - label: Refactoring (no functional changes, no API changes)
        - label: Build related changes
        - label: Documentation content changes
        - label: Other
    validations:
      required: true

  - type: input
    id: other-type
    attributes:
      label: If "Other", please describe
      placeholder: Describe the type of change

  - type: checkboxes
    id: breaking-change
    attributes:
      label: Breaking Change?
      description: Does this PR introduce a breaking change?
      options:
        - label: Yes
        - label: No
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description of change
      description: Please provide a brief description of what changes were made and why they were necessary
      placeholder: Describe your changes here
    validations:
      required: true

  - type: textarea
    id: testing
    attributes:
      label: How to test it
      description: Please provide instructions on how to test your changes
      placeholder: Steps to test the changes
    validations:
      required: true
